name: Déploiement sur Netlify
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master, demo, next]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Set branch name
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}
      - if: github.event_name == 'pull_request'
        name: 'Set site name for pull request deploy'
        run:
          echo "FR_SITE=deploy-preview-${{ github.event.number }}--syso.netlify.app/\${path}" >> $GITHUB_ENV;
          echo "EN_SITE=deploy-preview-${{ github.event.number }}--syso.netlify.app/\${path}?s%3Dm" >> $GITHUB_ENV;
      - if: github.event_name == 'push' && github.ref != 'refs/heads/master'
        name: 'Set site name for named branch deploy'
        run: 
          echo "FR_SITE=https://${{ steps.vars.outputs.branch }}.mon-entreprise.fr/\${path}" >> $GITHUB_ENV;
          echo "EN_SITE=https://${{ steps.vars.outputs.branch }}.mon-entreprise.fr/\${path}?s%3Dm" >> $GITHUB_ENV;
      - if: github.ref == 'refs/heads/master'
        name: 'Set site name for production deploy'
        run: 
          echo "FR_SITE=https://mon-entreprise.fr/\${path}" >> $GITHUB_ENV;
          echo "EN_SITE=https://mycompanyinfrance.fr/\${path}" >> $GITHUB_ENV
    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
      - run: yarn install
        env:
          # Secrets of all kinds for fetching stats & releases
          GITHUB_API_SECRET: ${{ secrets.GITHUB_TOKEN }}
          ZAMMAD_API_SECRET_KEY: ${{ secrets.ZAMMAD_API_SECRET_KEY }}
          ATINTERNET_API_SECRET_KEY: ${{ secrets.ATINTERNET_API_SECRET_KEY }}
          ATINTERNET_API_ACCESS_KEY: ${{ secrets.ATINTERNET_API_ACCESS_KEY }}
      - name: Build app
        run: yarn workspace mon-entreprise build
        env:
          # Deploy dependant config (change for production settings)
          AT_INTERNET_SITE_ID: ${{ github.ref == 'refs/heads/master' && 617190 || 617189 }}
          NODE_ENV: production
      - name: Deploy to Netlify
        id: deploy-netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './mon-entreprise/dist'
          netlify-config-path: ./netlify.toml
          production-branch: master
          production-deploy: ${{ github.ref == 'refs/heads/master' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: ${{ github.event_name == 'push' }}
          # Disabled because we create our own customized comment
          enable-pull-request-comment: false
          alias: ${{ github.event_name == 'push' && steps.vars.outputs.branch || format('deploy-preview-{0}',  github.event.number) }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }} #e.g. 1
          comment-author: 'github-actions[bot]'
          body-includes: netlify
      - name: Create comment
        if: steps.find-comment.outputs.comment-id == 0
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 La branche est déployée ! ${{ steps.deploy-netlify.outputs.deploy-url }}

            _Voir aussi : [version anglaise](${{ steps.deploy-netlify.outputs.deploy-url }}?s=m) | [site publicodes](${{ steps.deploy-netlify.outputs.deploy-url }}?s=p)_
